version: "3.5"

services:
  closing-loop:
    image: eldelto/tower:latest
    environment:
    networks:
      - tower_net
      - caddy_net
    expose:
      - 8080
    restart: always

networks:
  tower_net:
  caddy_net:
    name: caddy_net
    external: true
