name: Build & Deploy Tower

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install tools
      run: make init
    - name: Test
      run: make test
    - name: Build
      run: make
    # - name: Copy Deployment Artifacts to Node
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     port: ${{ secrets.PORT }}
    #     username: ${{ secrets.SSH_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     source: "deploy/docker-compose.yml"
    #     target: "/opt/tower/"
    # - name: Restart Service
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     port: ${{ secrets.PORT }}
    #     username: ${{ secrets.SSH_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script_stop: true
    #     script: |
    #       sysctl restart tower